
spring:
    application:
        name: auth-service

    config:
        import: "optional:configserver:http://localhost:8088/"

    main:
        allow-bean-definition-overriding: true
jwt:
    secret: hbhxvffsrbbfbeibeibiuhoieajfkopcwvouniebfhjbeibucbhbuebuhjrhjioJUInuJOpko;kthbdfsplBYOPiuhcufhuefuif 