
server:
    port: 8086

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
management:
    tracing:
        sampling:
            probability: 1.0

spring:
    application:
        name: api-gateway
    config:
        import: "optional:configserver:http://localhost:8088/"
      
    cloud:
        gateway:
            routes:
            - id: employee-service
              uri: lb://employee-service
              predicates:
                - Path=/employees/**

            - id: department-service
              uri: lb://department-service
              predicates:
                - Path=/departments/**

            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/auth/**


            # Configuration des paramètres pour accepter le cors origin
            default-filters:
                - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            globalcors:
                corsConfigurations:
                    '[/**]':
                        allowedOrigins: "http://127.0.0.1:5500,http://192.168.0.104:5500"
                        allowedHeaders: "*"
                        allowedMethods:
                            - GET
                            - POST
                            - PUT
                            - DELETE



